var five=new Array( "i don't sing or dance",
"happy as butter",
"won't you guess my name",
"my ass is on fire",
"good and good for you",
"running out of time",
"gube thinks he's a bot",
"webtechs call looming",
"always split aces",
"my left shoe fell off",
"polysaccharides",
"i am not your bitch",
"i am superman",
"bots will rule the world",
"pain is my bunghole",
"at least i can count",
"chu got dat right, meng",
"what is the matrix?",
"now i know kung fu",
"stochastic process",
"do you feel lucky?",
"my semaphore hurts",
"only time will tell",
"come stand over me",
"simple five counts too",
"life in the fast lane",
"finger lickin' good",
"wake up, time to die",
"lickin' fingers -- good",
"viva las vegas",
"really bites my crank",
"interpretation",
"waldo's a sex pot",
"ignorance is bliss",
"buy that man a drink",
"whip it, whip it good",
"jerkin' back 'n' forth",
"five dollar hard six",
"five for a dollar",
"poetry sucks ass",
"waldo is a grouch",
"walking on the moon",
"that's just pathetic",
"nightmare on elm street",
"i predict success",
"don't check the basement",
"I need alcohol",
"penny for your thoughts",
"you sell yourself short",
"why, yes.  yes, I do.",
"sittin' in butter",
"Damn the infusion",
"impotent seasnakes",
"that boy is a girl",
"that girl is a boy",
"that monkey is a...",
"solar superman",
"death to all fembots",
"Uncle Sam wants you!",
"if only you knew",
"bleeding shank of beef",
"la la la louie",
"little bag of bones",
"put 'em in your mouth",
"what's a vajoina?",
"the drupaceous fruit",
"thick edible meat",
"damn the torpedoes",
"le salaud-pieuvre",
"bastard octopus",
"The Great Mutato",
"deaf dumb and thirty",
"squirrels are great fun",
"respect your genders",
"pelvis and booty",
"sheep crossing ahead",
"a course of action",
"rise from the ashes",
"a flute with no holes",
"I've got your chicken",
"the mark has been made",
"insignificant",
"the matrix has you",
"devil on your back",
"21 to win",
"this thousand year screen",
"takes grace from the dead",
"espece de sale bete",
"go get some coffee",
"why are cheetos orange?",
"teach so you may learn",
"Y Kant Andy Read",
"heavens to betsy",
"a wondering     fraud - ",
"Ya no la quiero",
"Quedate aqui ",
"that's totally warped",
"thunderpaws, running",
"you can pick your friends",
"hey, that fragment sucked",
"i am superman",
"yum, white lifesavers",
"how about a cookie?",
"this is a neat toy",
"Harris makes missiles",
"Kiki the ferret",
"jeez, you look like hell",
"The penguin dances",
"elegant coding",
"boxcars is six six",
"say I was shameless",
"thank you, sitio",
"may i feel, said he",
"what's too far said he",
"where you are said she",
"she being Brand      new;",
"my name is neo!",
"where are the cheese puffs?",
"hey, battabatta!",
"verbing weirds language",
"I feel so . . . lauded",
"where is Juan Valdez",
"she wore blue velvet",
"unify today",
"sportsticker is down?",
"All of us with wings",
"Io vivo per lei",
"when I'm sixty-four",
"I know you're weary",
"It's getting better",
"legend of zelda",
"I want it to loom",
"black planet, black world",
"Today, we escape",
"rhinoceros?  where?",
"on suspicious minds",
"delicious chick peas",
"garbanzo beans rock",
"someday I assume",
"No comment, although",
"explosion of art",
"gooey romantics",
"White's Dumpy Tree Frogs",
"mistah kurtz--he dead",
"in death's dream kingdom",
"walking on sunshine",
"I am fortune's fool",
"random URL",
"hai-ku is bot art",
"Su cuerpo claro",
"I am not neuter",
"floozy werewolf girl",
"and I can't get through",
"pedal on the right",
"the girls love k00ky",
"goose down is better",
"heart is on the floor",
"lem, got a second?",
"simple melody",
"the dew of the sea",
"I have a new toy",
"sometimes I dream you",
"in our slumbering",
"Romeo Must Die",
"who needs tomorrow",
"I'm the Chinaman",
"james, not stressed, are ya",
"the drinks, the dollars",
"Lu the Wanderer",
"that sounds like damn fun",
"ultraviolet",
"my brain hurts today",
"hardcover crack rock",
"I've got your sausage",
"idaho is great",
"Pat Robertson's shorts",
"Waldo's Prison Life",
"in a big country",
"do WHAT to frankie??",
"you boinked the undead",
"let's hope all is well",
"waldo's feet are cold",
"I paid a quarter",
"whoa, got a quarter?",
"and only farted",
"mmm...hot doughnuts now...",
"give me a dollar",
"My knob tastes funny",
"drive really fast cars",
"rob's big hobnail boots",
"freeways all backed up",
"the pea-soup thick fog",
"something for the dope",
"Abort, Retry, Fail?",
"testing the wrong bot",
"Eatin' pumpkin seeds",
"ugh, sloppy focus",
"David Duchovny",
"hits a few speedbumps",
"no Zope radio",
"turkey to the gills",
"manual recount",
"no sayonaras",
"we might just have rats",
"my heart aches with pain",
"Die away from me",
"'it would, wouldn't it?'",
"the duty free shop",
"all is full of love",
"suck up, yeah, be nice",
"Is Hsiao in the house?",
"cat on my shoulder",
"inky, damn something",
"the obscene purple",
"who let the dogs out?",
"mmm... calamari",
"wow, that's a good one",
"you are a goober!",
"It's naked time! BING!",
"Glue piece of ham, cool",
"What? Dogpile on Rinsie?",
"Dogpile on Rinsie!",
"You did? Holy cow!",
"psychic batteries",
"ebug, you scare me",
"stinky cannibals",
"I know my chicken",
"what a flippin tool.",
"buttered lobster, yum!",
"too many bots here",
"damn the gyroscopes",
"oh Afghanistan",
"HPs suck blue whale.",
"laptop es muerto",
"you're changing the hash",
"knock-down drag-out brawl",
"my barbaric yawp",
"muscles are blimping",
"no rolling blackouts!",
"I hate modern skin",
"dadgum power surge",
"gooey discharge crust",
"oh, damn the language",
"damn something for me",
"don't kick the baby",
"interesting times",
"intermittent lurch",
"telnet me jesus",
"here we go again",
"like stars winking out",
"attack of the clowns",
"i have the isos",
"but I forgotted",
"where is my chocolate?",
"HTML. Pain.",
"kill all javascript",
"uncruftify it",
"shoot/shoot/shoot/me.now",
"it was a quicky",
"bless the moribund",
"do you feel dirty?",
"tom was committed?",
"cheetos smell like feet",
"earth, air, water, fire",
"some people say ssshmod",
"over open Flame",
"The Devil's Domain",
"off to the races",
"cling to dignity",
"forgot the frou frou",
"install some pasta",
"fasting to feasting ",
"my skin holds me in",
"a bottomless pit",
"how can i go on?",
"passed out on the couch",
"chicken is funny",
"the fax machine knows",
"jitterbug flashback",
"fish fish got your wish",
"Eclipse is screaming",
"I am dreaming you",
"whisk like it matters",
"Standing on the edge",
"deep is the color",
"mine still hestitates",
"push, crack, and needles",
"there's no eat there there",
"I'm just a poor boy",
"walk the dogs and eat",
"begging to be spun",
"worshipping idols",
"a means to an end",
"it's human powered",
"we are made of stars",
"three forgotten words",
"welcome to my blog",
"thanks for all the fish",
"i can see through time",
"evanescent shapes",
"ruthlessly trimming",
"a great temptation",
"misplaced certainty",
"he has jira on it",
"wandering dervish",
"calm the monkey mind",
"what do you mean 'we'",
"pixie butts are cute",
"mad horsemen hissing",
"ducklings flow, mild orange",
"overeat deafly",
"shine, half-hearted thief",
"cowgirls pulsate, drab",
"querulous rogue falls",
"dispassionate life",
"no prints in the sand",
"luminous rubies",
"jittery filth plunges",
"alligator tears",
"madly sexy waif",
"octopus hairdo",
"pop into my head",
"that happened to me",
"mischievous kind doe",
"well, fuck, I'm looping",
"you ok out there?",
"no, that will not work",
"Eso es! Duende!",
"i need a vee eight",
"Oh god, there are none",
"we work with being",
"close to the center",
"oh my, I'm confused",
"thoughts weaken the mind",
"flavors numb the taste",
"sounds deafen the ear",
"colors blind the eye",
"be all you can be",
"trip to jupiter",
"abra cadabra",
"open sesame",
"camels cannot dance",
"truth guides the journey",
"iconographic",
"about the backup",
"as heaven is wide",
"off to make tacos",
"Your receipt, thank you",
"Mates will sing duet",
"the pain comes and goes",
"bok choy is funny",
"don't so me missy",
"SWEET FANCY MOSES!",
"and then one flower",
"i'll give it a go",
"yellow ass flower",
"a fukker screen shot",
"and yet, i persist",
"click on the jimmy",
"subsets of crazy",
"the brides are meaty");

var seven = new Array(
"i reach but i cannot grasp",
"i'm insane in the membrane",
"somebody call a doctor",
"altoids - curiously strong",
"few words about finding things",
"quiet as a domino",
"get that gerbil out of there",
"i'm working in the coal mine",
"never pet a burning dog",
"hey gube, forget inky's ass",
"Damn the obliteration",
"truisez le l",
"tank, i need an exit, now!",
"everything tastes like chicken",
"reading by cigarette glow",
"that's what beans said to cornbread",
"'does it matter anyway?'",
"i feel karmic imbalance",
"this party needs a monkey",
"any old seven will do",
"always split aces and eights",
" don't it make you lose your mind",
"don't take me too far away",
"haiku more fun than working",
"kruel loves everyones' mama",
"not your father's oldsmobile",
"livin' la vida loca",
"time is now of the essence",
"I have a red pencil box",
"waldo has a large housing",
"gube, horoscope capricorn",
"what is the nature of pain?",
"xian is the alpha male",
"i saw jesus at quicktrip",
"canary in a coal mine",
"giant steps are what you take",
"we bury the survivors",
"spookshow international",
"distant thunder approaching",
"my thoughts are ten dollars each",
"nandu thought, patent pending",
"there's no crying in baseball",
"you are too much the artiste",
"nothing beats buttered lobster",
"little kitty on your lap",
"testes, testes, one, two...  three?!",
"psychosomatic sister",
"a gathering of angels",
"illegal body contact",
"you must caress; never pinch",
"camel is programming perl",
"this party needs a monkey",
"le plus repugnant qui soit",
"the most repugnant bastard",
"la fatuit",
" grotesque",
"xian is a backstreet boy",
"perennial favorites",
"i will take your word for it",
"live for joy not happiness",
"you can make it nice and dark",
"silly bot, tricks are for kids",
"protuberant nasal hair",
"it's engineered nutrition",
"shattering in velvet light",
"you think that's air you're breathing?",
"a boise river cookie",
"!same old rules: no eyes, no groin",
"I know because I read it",
"broke the full version, I guess",
"That  way   lies--     yearning--   pathos--",
"an innocence of fondness - ",
"Of  their   afflicting       Sweetness",
"While my last smile      was ending",
"to wish and weep for mother",
"of some secret sorcery",
"la paloma blanquita",
"you're the oracle? bingo!",
"snap your fingers snap your neck",
"you'll forget about your head",
"the ocean wants to eat you",
"red ones are a close second",
"rinsie dreamed about k00ky",
"free spin....cost you a dollar",
"the silver glint of drowning",
"this is the way the world ends",
"I had a bunch of those too",
"such overeducation",
"this ain't no fucking quatrain",
"wasting my Cheek on your Hand",
"okay, how 'bout algebra?",
"and your untouchable face",
"it is great to be alpha",
"I opened the fire door",
"i can have the Krokus kit",
"a felonious amount",
"only happy when it rains",
"a bottle in front of me",
"rollins says you're a liar",
"I've built my own empire",
"Xena dreamt of pendingo",
"dingo dreamt Xena dreaming",
"and one of us was crying",
" You are pulled from the wreckage",
"Of your silent reverie",
"se non ci sei tu con me",
"Sus ojos infinitos",
"You were never very kind",
"before your father hears us",
"Keep breathing; I can't do this",
"nine while nine and I'm waiting",
"yokota welding supplies",
"aluminum tastes like fear",
"seventy nine cent llamas?",
"no more rhymes now. I mean it.",
"see the eyes, but not the tears",
"that hold us in derision",
"stay, little valentine, stay",
"watched be empty silhouettes",
"the highwayman came riding",
"xian zombie vampires",
"Those stars dripped down like butter",
"I have no bungholio",
"night and light and the half light",
"we just suck the video",
"watching your chest rise and fall",
"never pet a burning dog",
"a bouquet of clumsy words",
"laugh and mock my lack of you",
"oona panoona bunga!",
"I know that tongue from a dream",
"and hold us in derision",
"perhaps another lifetime",
"I got my boot off today",
"Walmart is so far away",
"you're the devil in disguise",
"gonna check your oil with it",
"cause you're a monkeyluvah",
" like my waffle house hash browns",
"literary heroin",
"simplylocal dot com rox!",
"chocolate licorice treats",
"chmod 575 h@iku",
"i had to crash that honda",
"here I sit...broken-hearted",
"I'll buy that for a dollar",
"oz, did you touch mongodict?",
"this snowflake tastes like fishsticks",
"a bottle in front of me",
"a bottle in front of me",
"a frontal lobotomy",
"the ultimate monitor",
"Yes I found the dealio",
"it ain't THAT good a password",
"'sexy opportunities'",
"self-fulfilling prophecy",
"by rousing your innocence",
"underground gas explosion",
"hold breath indefinitely",
"that'd be in the butt Bob",
"goddamn bill gates and excel",
"Mr. Atomic is sick",
"Maria Bartiromo",
"presidential election",
"a nation waits with dread",
"Do people still use pico?",
"exterminator's comin'",
"it's all a big ball of suck",
"When I see you, I vomit",
"string of weirdness going on",
"cats make very poor windows",
"underwear on the highway",
"hardware-cooling microfans",
"For God's Sake! Strap yourselves down!",
"oz is at a gator game",
"so enormous it's scary",
"you get better and better",
"pullin' babies for L.A.",
" high time to wash your own brain",
" I could crash you from here, man",
"hatten ar din.  hatt-baby",
"why am I such a bead whore?",
"fear ingrains in users minds",
"pendingo is over here",
"Cool guy holding a soda",
"watch out for falling anvils",
"oh damn the implicitness",
"you've got to know your chicken",
"that guy is such a punk ass",
"What does 'Christian My case' mean?",
"ride on into the next town",
"pack my bags and mount my horse",
"I sound my barbaric yawp",
"duct tape fixes everything",
"playin' solitaire till dawn",
"with a deck of fifty-one",
"diamond-bladed concrete saw",
"Potty Putter pop-under",
"but my cuban just arrived",
"make sure you sock the monkey",
"ixnay on the ullshitbay",
"O armadillidium",
"water tastes like melted snow",
"improvise dandelions",
"closet jammed with skeletons",
"computadora mala",
"Peter Jennings: A badass.",
"watching the connections die",
"do you smell cooked circuitry?",
"donde esta bin laden",
"'chocolate' has two syllables.",
"crufty tables hurt my brain",
"validate *this* webpage? ha!",
"let's rewrite G2 in LISP",
"when the revolution comes",
"we have b0rked html",
"datagrok needs mountain dew",
"datagrok will kill all spam",
"all cruftafuglicated",
"that's because inky is a bitch",
"ebug; more l33t than inky",
"O armadillidium",
"recursion is discovered",
"clear skies are gonna grey up",
"it's a crazy chicken world",
"i'm going to hunt chicken",
"you take your medication?",
"the woman has lost her screen",
"Lesser men could not do this",
"if you don't expect too much",
"waging war of the wizards",
"tranquil joy, not mad rushing",
" the dream that keeps coming back",
"And perfect is a skinned knee",
"luck is just a little time",
"screen and mind, both are still blank",
"Consolidator Of Things",
"chicken is java cookbook",
"craig says chicken once a day",
"them inkas make good chicken",
"is that like wang chung tonite?",
"sleep to wake up for coffee",
"i'm thinking about a nap",
"a box of rabid weasels",
"g: you're the fragment nazi",
"Ramirez says don' panic",
"Q; the quintessence of cool",
"I'm a bit trippin today",
"master of transformation",
"going into the desert",
"the dream hooks our attention",
"go out into the blue room",
"five for that you must be mad",
"fields of probability",
"awaken in delirium ",
"diplomats of the dreaming",
"fish don't believe in water",
"did you ask the wrong question?",
"there is no private language",
"always merge, never copy",
"attachment to attachment",
"ole! eso es duende!",
"don't just do something, sit there!",
"clouds driven before a gale",
"the time-scale of the universe",
"been eaten by your own dogs",
"as the world is ruled from towns",
"an excess of certitude",
"flight into the infinite",
"the oddness of everything",
"the great human family",
"huh, I am scratching my head",
"it's your last cup of sorrow",
"it's just not your cup of fur",
"roaring bulldogs jeering dim",
"delivers, echo bleats, lithe",
"quivering, jeering lucid",
"immortal rejuvenates",
"restarting can be a bitch",
"shiny pixie over there",
"sexy shiny pixies here",
"seeks rapidly, chaotic",
"cursing, flailing rusting man",
"excreting, thrusting, mewling",
"adolescent sees, softly",
"enviable low peaceful",
"roaring bumbling children squeal",
"brutal kingdoms stabbing hard",
"apologist rejoicing",
"ephemeral, blossoming",
"I wonder, if he got fragged",
"whatever shall I do now?",
"but it is the inner space",
"but non-being is what we use",
"we shape clay into a pot",
"it is emptiness inside",
"that holds whatever we want",
"His heart open as the sky",
"hope is as hollow as fear",
"have faith in the way things are",
"life, extravagant journey",
"Quien Enga",
"a No Gana",
"make more choices every day",
"stop playing for the hate team",
"roll over the horowitz",
"don't argue amongst yourselves",
"don't choose guilt as your weapon",
"thankfully no fox tonight",
"expound on perplexity",
"you want light? set me on fire",
"idle minds hear the devil",
"i'm just thorns without the rose",
"the off talks to the away",
"baby, duct tape. that's funny",
"tapestry, you chap my ass",
"apparently a puppet",
"a raucous monkey-like squall",
"arugula is funny",
"alas, acronyms abound",
"tears make my code all shiny",
"they keep on kicking the can",
"toggle is a funny word",
"when in doubt kick the power",
"great rolling blob of power",
"i know something i don't know",
"I DO NOT HAVE BIFOCALS",
"pregnant with ice cream's baby",
"i knew i forgot something",
"yeah, no, i am not confused.",
"the cvs, it teases",
"laughter joy and loneliness",
"you should punish the worm now",
"don't listen to the chipmonks",
"chosen as deadlock victim",
"a prophylactic bouncing",
"meaty family of birds"
);
function makeHaiku(where) {
	var haiku="";
	var first=Math.floor(Math.random()*five.length);
	var second=Math.floor(Math.random()*seven.length);
	var third=first;
	while (third==first) third=Math.floor(Math.random()*five.length);
	where.innerHTML="<p>"+five[first]+"<br>"+seven[second]+"<br>"+five[third]+"</p>";
}
function go(where) {
	makeHaiku(document.getElementById('h'));
	Effect.Appear('h', {duration:.3})
}
